### ISSUE TITLE
Modal im nachhinein füllen

### ISSUE THREAD

**Issue by danielhoover** [dariohana21/Web-Project#1]
Hallo Herr Brozovic,

ich war mir jetzt nicht sicher ob mein kurzer Tipp schon ausgereicht hat. Bevor Sie sich jetzt in die weiten des Internets begeben und vielleicht sogar schlimme Dinge in Foren lesen möchte ich Sie auf die Dinge stoßen die wir in der Vorlesung und Übung besprochen haben.

AJAX ermöglicht uns generell, einen Request abzusetzen und diesen mit JavaScript auszuwerten. Das ist deswegen ganz praktisch weil wir uns theoretisch eine Information holen können die wir aktuell nicht haben. Beispiele: ein View (HTML Markup) holen, oder wir übergeben eine Emailadresse und lassen diese auf Gültigkeit prüfen, oder Holen das aktuelle Datum. etc. Dafür brauchen wir aber irgendetwas "intelligentes", dass sowas machen kann. Das Zauberwort lautet hier API. Also eine eigene Schnittstelle. Wir müssen also eine eigene Schnittstelle definieren und fragen dann an über AJAX was wir eben haben wollen.

Im Baseproject habe ich das was Sie sich vorstellen bereits realisiert. Schauen Sie sich hierzu bitte folgende Dateien an:

[Die Schnittstelle](https://github.com/danielhoover/baseproject/blob/master/includes/restservices/Address.php)
Anmerkung: Die Schnittstelle kann weit mehr als nur ein leeres oder gefülltes Formular zurückzugeben - sie speichert auch die Werte aus dem Formular und reagiert aufs löschen.

[Die Definition der "route" bei einer Schnittstelle](https://github.com/danielhoover/baseproject/blob/master/includes/restservices.php)

Anmerkung: Im Beispiel ist eine Klasse Address definiert die über api/address/ aufgerufen wird. Hätten wir eine Klasse Wasserhahn würde diese über api/wasserhahn/ aufgerufen werden.

[Das JavaScript zum absetzen und auswerten des AJAX Requests auf die Schnittstelle](https://github.com/danielhoover/baseproject/blob/master/js/core.js)

Ich hoffe das hilft Ihnen.

Sollten Sie Fragen dazu haben, dann kommentieren Sie einfach dieses Issue.

Herzliche Grüße
Daniel Hoover

**Comment by superdariobroz** [comment]
Hallo Herr Hoover, 
ich habe nun probiert das Modal für unseren "Konto Erstellen" Button zu befüllen. Folgende Fehlermeldung wird mir in der Konsole ausgegeben. 
![screenshot 2017-06-27 17 45 48](https://user-images.githubusercontent.com/28716127/27596690-92ecc55c-5b60-11e7-9b47-9a8e79d42370.png)

Hier einmal die core.js 
(der Teil mir dem Selektor newAccount ist von mir)

```JavaScript


$(document).ready(function () {


    $('.newAccount').click(function () {

        dataToSend = {cmd: "getKontoHinzufuegen"};

        $.ajax({
            url: 'klugeDateiKonto.php',
            method: "post",
            data: dataToSend,
            success: function (dataReceived) {
                //console.log(dataReceived);

                var myModal = $('#test2');

                myModal.find('.modal-body').html(dataReceived.view);

                $('#test2').modal('show'); // ZEILE 20 ZEILE 20  ZEILE 20  ZEILE 20  ZEILE 20   ZEILE 20

            }
        });

    });


    $('.editBill, .newBill').click(function () {
        var billId = $(this).attr('data-id');

        dataToSend = {cmd: "getBillView"};

        //if there is an id given...
        if (typeof billId !== 'undefined') {
            dataToSend.push({id: billId});
        }

        $.ajax({
            url: 'klugeDatei.php',
            method: "post",
            data: dataToSend,
            success: function (dataReceived) {
                //console.log(dataReceived);

                var myModal = $('#test2');

                if (typeof billId !== 'undefined') {
                    myModal.find('.modal-title').html('Rechnung Nummer ' + billId + ' bearbeiten');
                } else {
                    myModal.find('.modal-title').html('Neue Rechnung erstellen');
                }

                myModal.find('.modal-body').html(dataReceived.view);


                $('#test2').modal('show');

            }
        });
        //console.log($(this).attr('data-id'));
    });


});

``

außerdem eine neue "klugeDateiKonto" falls das der richtige Ansatz ist: 


```php

<?php
require_once('includes/initialize.php');

if(!empty($_POST) && isset($_POST['cmd']) && $_POST['cmd'] == 'getKontoHinzufuegen')
{
    //eine logik die mir den view holt
    $view = new View('kontoHinzufuegen', 'kontoHinzufuegen');

    //die die daten an den view übergibt
    //die mir den view so zurückgibt, dass jquery was damit anfangen kann
    // set the status
    header('HTTP/1.1 200 OK');
    // set the content type
    header('Content-type: application/json');
    // set X-UA-Compatible for IE9
    header('X-UA-Compatible: IE=edge, chrome=1');

    echo json_encode(array('view' => $view->parse()));
}

```

**Comment by superdariobroz** [comment]
Eine weitere Fehlermeldung kommt wenn man auf den Bearbeiten Glyphicon klickt. Dieser hat den Selektor "editBill".  (dataToSend.push is not a function) 
Da hatten sie was probiert und wir haben nicht mehr nachgesehen ob es funktioniert.

**Comment by superdariobroz** [comment]
Vermutlich hätte ich statt eine neue "Kluge Datei" zu erstellen auch einfach eine neue If Anweisung in die alte schrieben können, oder? (keine Sorge, die alte habe ich natürlich nicht gelöscht)

**Comment by danielhoover** [comment]
Hallo Herr Brozovic,

also zu Ihrem Fehler mit Uncaught Type Error:

sehen Sie sich bitte folgende Dateien ganz genau an:

includes/views/billForm.php (da passt alles)

und jetzt noch die Dateien wo es zu Schwierigkeiten kommt:

includes/views/kontoHinzufuegen.php
sowie
includes/views/rechnungErstellen.php

Da scheint ziemlich am Anfang etwas anders zu sein. So anders, dass es bei billForm.php funktioniert... (sehen Sie es?)

Sie müssen arg aufpassen was Sie im View als HTML Markup zurückgeben sofern Sie das Markup komplett so in Ihr Modal einfügen. Was glauben Sie wie gut das JavaScript findet wenn auf der Seite plötzlich zweimal

```html
<html>
<head>
[...]
```

zu finden ist? Das führt zu massiven Fehlern. Das heißt, dass Sie in einer derartigen Datei keinen header und keinen footer einbinden dürfen.

Zur Ihrer Frage:

> Vermutlich hätte ich statt eine neue "Kluge Datei" zu erstellen auch einfach eine neue If Anweisung in die alte schrieben können, oder? (keine Sorge, die alte habe ich natürlich nicht gelöscht)

Ja hätten Sie! :-) Geht beides.

Herzliche Grüße
Daniel Hoover

**Comment by danielhoover** [comment]
So - für das andere Problem mit editModal:

Ganz dringend fügen Sie bitte in Ihre klugeDatei.php folgendes ein:

statt

```php
echo json_encode(array('view' => $view->parse()));
```

bitte folgendes

```php
echo json_encode(array('view' => $view->parse()));
exit();
```

andernfalls geht er leider in ihr zweites if rein und löscht die rechnung...

Gut - die Fehlermeldung bekommen Sie weg wenn Sie folgendes in der core.js ausbessern:

```javascript
dataToSend = [{name: "cmd", value: "getBillView"}];

//if there is an id given...
if (typeof billId !== 'undefined') {
       dataToSend.push({name: "id", value: billId});
}
```

Das sollte auch schon alles gewesen sein.

.push ist nur eine Methode von Arrays - das hatte ich vorher falsch gemacht. Wie es richtig geht sehen Sie oben.

Herzliche Grüße
Daniel Hoover

**Comment by superdariobroz** [comment]
Vielen Dank! Das hat sehr geholfen.

**Comment by superdariobroz** [comment]
Hallo Herr Hoover,
wir hängen nun am nächsten Problem fest. 
Der Button Speichert zwar das Konto. Jedoch wird dann die kontoHinzufügen.php geladen. 
Muss für den Button zusätzlich in der core.js definiert werden was passieren soll? Muss die logik aus dem Controller dann in die "Kluge Datei" und über ajax die index.php neu geladen werden?
Entschuldigung für die vielen Fragen. 
Schöne Grüße 
Dario

**Comment by danielhoover** [comment]
Hallo Herr Brozovic,

das kommt darauf an, was Sie gerne wollen, das passieren soll. Bevor ich Ihnen also sagen kann was Sie wo definieren sollten müsste ich wissen was Sie gerne hätten was vom Ablauf her passiert. Daher meine Frage an Sie: was soll nachdem ich auf "speichern" geklickt habe passieren?

Soll im Erfolgsfall das Modal geschlossen und eine Erfolgsmeldung ausgegeben werden?
Und soll im Fehlerfall eine Fehlermeldung ausgegeben werden?

Falls Ihre Antworten darauf "ja" lauten - dann lautet auch hier die Magie "AJAX".

D.h. Sie dürfen den Submit nicht normal wie über das Formular ablaufen lassen sondern Sie müssen den versuchten Submit abfangen und einen "Submit" per AJAX ausführen. Dann muss Ihre neue Kluge Datei - in dem aktuellen Fall ist das laut form action="" Eintrag der Controller der für die URL kontoHinzufuegen zuständig ist in der Lage sein das POST entsprechend zu verarbeiten und eine Antwort zurückzugeben ähnlich wie Sie das bereits in der klugeDatei.php gemacht haben.

Vielleicht noch die Frage Submit per AJAX - Submit abfangen? Das würden Sie wie folgt in JavaScript machen:

```html
<script type="text/javascript">
$('#kontoHinzufuegen-form').submit(function(e) {
     e.preventDefault(); //Submit abgefangen

     var urlToSendFormularTo = $(this).attr('action');
     var variablesFromFormular = $(this).serialize(); //nice function which gets all fields from the form for us

     $.ajax({
          url: urlToSendFormularTo,
          method: "post",
          data: variablesFromFormular,
          success: function(dataReceived) {
               //check values in dataReceived to see if everything was fine
               //if yes - say everything good to the user
                    //after a while (i.e. 3 seconds) reload page
                    // close modal not really necessary - but we can do it (after 3 seconds the page will be reloaded anyway)
               //if not - mark fields as error fields and/or display error message to the user
          }
     });
});
</script>
```

Das machen Sie in Ihren View kontoHinzufuegen.php an das Ende - warum? Weil Sie da sicher sein können, dass $('#kontoHinzufuegen-form') nicht fehlschlägt - weil es ja vorher definiert wurde.

Hilft Ihnen das weiter?

Herzliche Grüße
Daniel Hoover

**Comment by superdariobroz** [comment]
Danke das hat funktioniert!
Nun haben wir in der in dem billForm eine neues, verstecktes feld hinzugefügt. Das Feld "kontoid".
In dem jScript (welches sich in der billForm befindet) soll nun überprüft werden ob das Feld kontoid "undefined" ist und falls ja, soll die kontoid des jeweiligen Kontos eingefügt werden. Nun wissen wir nicht wie wir diese herbekommen. Evtl kann man sie aus der index.php bekommen, jedoch kommt ma da mit $this nicht hin. 
Falls das schon für einen 1er reicht, würden wir aufhören Sie zu belästigen :). Konten anlegen, Rechnungen löschen und bearbeiten funktioniert mittlerweile. Wir sind schon nocht motiviert, es gibt aber noch 3 andere Prüfungen zu schreiben. 

Herzliche Grüße
Dario

**Comment by danielhoover** [comment]
Ich vermute, dass Sie inzwischen genug Zeit in das Projekt investiert haben. Konzentrieren Sie sich dann mal auf Ihre 3 anderen Prüfungen... :-)

**Comment by superdariobroz** [comment]
Rechnungen bearbeiten funktioniert doch noch nicht.
```

VM1550:3 Uncaught SyntaxError: Unexpected token )
    at p (jquery-3.2.1.min.js:2)
    at Ja (jquery-3.2.1.min.js:3)
    at r.fn.init.append (jquery-3.2.1.min.js:3)
    at r.fn.init.<anonymous> (jquery-3.2.1.min.js:3)
    at T (jquery-3.2.1.min.js:3)
    at r.fn.init.html (jquery-3.2.1.min.js:3)
    at Object.success (core.js:52)
    at i (jquery-3.2.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js:2)
    at A (jquery-3.2.1.min.js:4)
p	@	jquery-3.2.1.min.js:2
Ja	@	jquery-3.2.1.min.js:3
append	@	jquery-3.2.1.min.js:3
(anonymous)	@	jquery-3.2.1.min.js:3
T	@	jquery-3.2.1.min.js:3
html	@	jquery-3.2.1.min.js:3
success	@	core.js:52
i	@	jquery-3.2.1.min.js:2
fireWith	@	jquery-3.2.1.min.js:2
A	@	jquery-3.2.1.min.js:4
(anonymous)	@	jquery-3.2.1.min.js:4

```

das kommt bereits beim Drücken auf das bearbeiten Symbol

**Comment by danielhoover** [comment]
Sofern Sie im Chrome entwickeln sollte ganz rechts bei der Fehlermeldung oben die Möglichkeit gegeben sein drauf zu klicken. Da werden Sie zu der Stelle geführt die der Chrome nicht so gut findet... Und wenn Sie mich fragen - recht hat er der Chrome... ;-)

<img width="1316" alt="bildschirmfoto 2017-06-29 um 17 45 14" src="https://user-images.githubusercontent.com/4067099/27697015-65e0c880-5cf3-11e7-95ec-1011efd722f2.png">

**Comment by superdariobroz** [comment]
Ja, Fehlermeldung ist behoben :). Uns ist eingefallen das es mit dem Bearbeiten schon vorher nicht ging.
